title: David Pan
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;">
  <strong>Academic Background:</strong> 
  <br>
  Masters in Urban Spatial Analytics | Domain specialization in Real Estate
  <br>
  <abbr title="a private Ivy League university in Philadelphia, PA">University of Pennsylvania (Penn)</abbr> 
  <br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  <strong>Work History (see Resume):</strong> 
  <br>
  3+ years of cumulative professional and internship experience spanning several industries: GIS/spatial informatics*** (inland water research, regional economic development, regional health management), academic/education, IT/database development (banking), customer service (skylight manufacturing), traffic & noise impact analysis + surveying (transportation)
  <br>
  <i>***primary domain expertise</i>
  <br><br>
  Employers (excluding contracts): Southlake Hospital, Environment Canada's National Inland Water Research Institute, WSP Global, VELUX Canada Inc, University of Waterloo, Ministry of Economic Development  
  <br>
  </p>
  <a href="https://www.linkedin.com/in/yuanrongpan/">LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y
