title: David (Y.R.) Pan
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;color: #00008B;">
  <br>
  RE Developer
  <br>
  <strong>Academic background:</strong> 
  <br>
  Spatial Informatics (MUSA'21)
  <br>
  Domain specialization in Real Estate (Wharton)
  <br>
  <abbr title="private Ivy League university in Philadelphia, PA">University of Pennsylvania (Penn)</abbr> 
  <br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y
