title: David Pan 
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;">
  <strong>Academic Background:</strong> 
  <br>
  Master of Urban Spatial Analytics | Domain specialization in Real Estate
  <br>
  <abbr title="a private Ivy League university in Philadelphia, PA">University of Pennsylvania (Penn)</abbr> 
  <br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  <strong>Work History:</strong> 
  <br>
  3+ years of cumulative professional and internship experience across multiple industries: inland water research, GIS/spatial informatics, economic development, academic/education, IT/database development, field & traffic surveying (See Resume for details)
  <br>
  </p>
  <a href="https://www.linkedin.com/in/yuanrongpan/">LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y 
