title: David Pan
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;">
  <strong>Academic Background:</strong> 
  <br>
  Spatial Informatics (MUSA'21)
  <br>
  <abbr title="a private Ivy League university in Philadelphia, PA">University of Pennsylvania (Penn)</abbr> 
  <br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  <strong>Profession:</strong> 
  <br>
  Physical Scientist of Environment Canada, Science & Technology Branch, National Inland Water Research Institute
  </p>
  <a href="https://www.linkedin.com/in/yuanrongpan/">LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y
