title: David Pan
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;color: #29465B;">
  <br>
  Chairman, World Ranking, Inc.
  <br>
  <br>
  <strong>Alma mater:</strong> 
  <br>
  Penn, MUSA'21
  <br>
  RE Domain specialization
  Alum connections: yrpan@alumni.upenn.edu
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y
