title: David Pan 
logo: "/images/logo.png?raw=true" 
description: > 
  <p style= "font-family: Garamond,Baskerville,Baskerville Old Face,Hoefler Text,Times New Roman,serif;
  font-weight: 400;font-style: normal;line-height: 1.5;">
  <strong>Academic Background:</strong> 
  <br>
  Master of Urban Spatial Analytics | Domain specialization in Real Estate
  <br>
  <abbr title="a private Ivy League university in Philadelphia, PA">University of Pennsylvania (Penn)</abbr> 
  <br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  <strong>Selected Professional Experience:</strong> 
  <br>
  Consultant Database Developer (under subcontract to) RBC Royal Bank (2021-2022)
  <br>
  Modeler - Scientific Support (2019-2020), Environment Canada | Science & Technology Branch
  <br>
  </p>
  <a href="https://www.linkedin.com/in/yuanrongpan/">LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y 
