title: David (Yuan Rong) Pan 
logo: "/images/bio-photo_small.jpg?raw=true" 
description: > 
  <strong>Education:</strong> 
  <br><br>
  Master of Urban Spatial Analytics | Domain specialization in Real Estate
  <br><br>
  <abbr title="a private Ivy League university in Philadelphia, PA">University of Pennsylvania</abbr> | Weitzman & Wharton Schools
  <br><br>
  <strong>Email:</strong> yrpan@alumni.upenn.edu
  <br><br>
  <strong>Selected Professional Experience:</strong> 
  <br><br>
  Modeler - Scientific Support (2019-2020), Environment Canada | Science & Technology Branch
  <br><br>
  <a href="https://www.linkedin.com/in/yuanrongpan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-DT87ZHZK9Y 
